### PR TITLE
Check changes

### PR DESCRIPTION
**Pull request by tarunlalwani**
Checking changes

### CODE REVIEW

**Comment by quirimmo** [comment]
Hi @tarunlalwani, thanks a lot for your help. Unfortunately as I told you before, the build still seems to fail for the reasons I said. But again, thanks a lot for the help :)

**Comment by quirimmo** [comment]
Hi @tarunlalwani , Just looking to your changes and you're going to the direction of manually starting `webdriver-manager` and then use the address for connecting from protractor. I am already able to do that, but that's not the road I would like to cross. See the question on SO, there is the following at the end: 

> **p.s. I already did it on other projects with Travis running manually the webdriver-manager and then pointing to the selenium address from the protractor.config.js, but I don't want that solution and I want to go on through the seleniumServerJar property, because in this way it will run everything alone without any need of starting manually the webdriver-manager**

**Comment by tarunlalwani** [comment]
@quirimmo , don't watch this thread till I ping again. I will be doing some trial and errors

**Comment by tarunlalwani** [comment]
@quirimmo , the issue for jar is fixed. I guess you have not specified the browser capabilities in `protractor.config.js` and that is why the new failure. Do you want to take it from here or you will be able to manage?

**Comment by quirimmo** [comment]
Hi @tarunlalwani  

So first of all, thanks really a lot for your help. 

You still have this code: 
```
seleniumAddress: process.env.SELENIUM_SERVER_JAR || 'http://127.0.0.1:4444/wd/hub/'
```
Which is actually wrong because it doesn't use the expected properties from `gulp-protractor` called `seleniumServerJar` in order to execute all alone.
I already fixed the issue few time ago, now I am fighting with a new one :D 
I found this wonderful link where she explain that you need to install it: 
https://github.com/angular/protractor/issues/3225

So I did this in my install block:

```
install:
  - npm install
  - node_modules/protractor/bin/webdriver-manager update
```

And this in my `protractor.config.js`:

```
const SELENIUM_FOLDER = './node_modules/protractor/node_modules/webdriver-manager/selenium';
const fs = require('fs');
let res, seleniumVersion;
fs.readdirSync(SELENIUM_FOLDER).forEach(file => {
    res = file.match(/selenium-server-standalone-(\d{1}.\d{1}.\d{1}).jar/i);
    if (res) {
        seleniumVersion = res[1];
    } 
})
if (!seleniumVersion) {
    throw new Error('No selenium server jar found inside your protractor node_modules subfolder');
}
```

and this:

`seleniumServerJar: `./node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-${seleniumVersion}.jar``

And everything works like a charm. 

However, thanks a million again for all your help, and again, if you would like to, and you are interested in, I would be really happy if you want to contribute to this project. 

Regards

**Pull request closed without merging**
